### PR TITLE
Initialization code refactored

### PR DESCRIPTION
**Pull request by ypahalajani**
Made following enhancements:

1. Readline support added in place of sget (which is deprecated by npm)
2. Promise workflow implemented

### CODE REVIEW

**Comment by btk** [comment]
Hey, @ypahalajani this is actually great, but I had merged a new feature, that allows users to choose between artist listing or track listing. 

_See #13_ 

In this new feature we also used `sget`, do you think can you form from the current master and swap the sget with `readline`, since I haven't used it `readline` before?

And I love the promise workflow, waiting on your new pull request.

**Comment by ypahalajani** [comment]
@btk: definitely, I'll refactor the code with respect to readline in place of sget

**Comment by ypahalajani** [comment]
@btk : PR has been updated. Please review the new code. I've added **required** support in promise i.e. if a variable is required ,the user does not enter anything and required field is set to false, the promise is not rejected and the flow goes as it is intended to go.

**Comment by btk** [comment]
This is great, I also love the comments. 

But another contributor made the variable "metric" so I'm not sure about calling it metric. For now I'm merging this, we might change it to, "type" or something more clear "listingType".

Thank you for your contribution.

**Pull request merged**
